# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we are going to cover:

* Introduction to tensors
* getting information to tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs or TensorFlow (or TPUs)
* Exercises to try for yourself!

Introduction to Tensors

In [2]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)  # tf.constant Creates a constant tensor from a tensor-like object.
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor(ndim stands for number of dimensions)
print(scalar.ndim)

0


In [5]:
# Create Vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check dimension of vector
vector.ndim

1

In [7]:
# Create a matrix (matrix has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
# Ckeck dimension of vector
matrix.ndim

2

In [9]:
# Create another matrix with data type
another_matrix = tf.constant([[10., 5.],[4.,3.],[8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 4.,  3.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18],
                       ]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

What we have created so far:
* Scalar: a single number
* Vector: a number with direction(e.g wind speed with direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

In [13]:
# Creating Tensors with tf.variables
# Create same tensors with tf.Variable() as above
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try change one of the elements in our changable tensor
changable_tensor[0] = 7
changable_tensor

TypeError: ignored

In [15]:
# How about try .assign

import tensorflow as tf
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
changable_tensor[0].assign(7)
changable_tensor

# Let's try change our unchangable tensor
unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: ignored

Creating random tensors

Random tensors are tensors of some arbitary size which contains random numbers.

In [16]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproductibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [17]:
# Schuffle the order of elements in a tensor
# Schuffle a tensor (valuable for when you want to schuffle data so the inherent order doesn't effect learning)

not_schuffled = tf.constant([[10, 7],
                             [3, 4],
                             [2, 5]
                             ])

# Schuffle our non_schuffled
shuffle = tf.random.shuffle(not_schuffled)
shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [18]:
# shuffle our non-shuffled tensor
import tensorflow as tf
not_schuffled = tf.constant([[10, 7],
                             [3, 4],
                             [2, 5]
                             ])
tf.random.set_seed(42)  # Global level random seed
tf.random.shuffle(not_schuffled, seed=42)  # Operation level random seed


# It looks like if we want our suffled tensors to be in same order, we've to use the global level random seed as well as the operation level random seed.
# Rule: 4 If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [19]:
# Create tensor with ones
tf.ones([3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [20]:
# Create tensor with zeros
tf.zeros(shape=(5,4))

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on GPU much faster computing.

In [21]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)  # Range (1, 25) generates 24 number
tensor_a = tf.constant(numpy_A)
tensor_b = tf.constant(numpy_A, shape=(4 ,3, 2)) # While reshaping the product should be 24 just like 2 * 3 * 4 = 24
tensor_a
tensor_b

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

Getting Information from tensors
When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [22]:
# Create rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor
rank_4_tensor.ndim

4

In [23]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [24]:
rank_4_tensor.shape, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
# get various attributes of our tensor
print("Data Type of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensors:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))

Data Type of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensors: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


Indexing Tensors

Tensors can be indexed just like Python lists.

In [26]:
# Get the first two elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# Get the first element from each element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# Create a rank 2 tensor( 2 dimensions )
rank_2_tensor = tf.constant([[10, 7], [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [29]:
# Get the last item of each of row of our 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [30]:
# Add in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]  # newaxis add in extra dimension
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [31]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1)  # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [32]:
tf.expand_dims(rank_2_tensor, axis=0)  # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

Manipulating tensors (tensors operations)

Basic Operations
`+` , `-` , `*`, `/`

In [33]:
# You can add values to a tensor using the addition operator

tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [34]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [35]:
# Multiplication also works

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
# Subtraction also works

tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [37]:
# We can use the tensorflow built-in function too

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Matrix Multiplication

In Machine Learning, matrix multiliplication is one of the most common tensor operations.

In [38]:
# Matrix multiplication in tensorflow
a = tf.constant([[1,2,7],[7,2,1],[3,3,3,]])
b = tf.constant([[2,5],[6,7],[1,8]])
tf.matmul(a, b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[21, 75],
       [27, 57],
       [27, 60]], dtype=int32)>

In [41]:
# Matrix multiplication with Python Operator "@"

c = a @ b