In [1]:
import tensorflow as tf

One-Hot Encoding tensors

In [2]:
# Create a list of indices

some_list = [0,1,2,3] # could be red, green, blue, purple

tf.one_hot(some_list, depth=4)  # One hot encode our list of indices

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [3]:
A = [0,1,1,2]
tf.one_hot(A, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [4]:
# Specify custom values for one hot encoding

tf.one_hot(some_list, depth=4, on_value="Hello", off_value="World")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Hello', b'World', b'World', b'World'],
       [b'World', b'Hello', b'World', b'World'],
       [b'World', b'World', b'Hello', b'World'],
       [b'World', b'World', b'World', b'Hello']], dtype=object)>

Squaring, Logs, Square Root

In [7]:
# Create a new tensor

H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [8]:
# Square it

tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [12]:
# Find square root

tf.math.sqrt(H)

InvalidArgumentError: ignored

In [11]:
# Find square root

tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [13]:
# Find log

tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>